name: 'Deploy Gatsby Application'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: 'gh-pages'
          access-token: ${{ secrets.AUTH_GITHUB_TOKEN }}
