name: 'Deploy Gatsby Application'

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GATSBY_DOMAIN: ${{ secrets.GATSBY_DOMAIN }}
          DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}
          DIRECTUS_PROJECT: ${{ secrets.DIRECTUS_PROJECT }}
          DIRECTUS_TOKEN: ${{ secrets.DIRECTUS_TOKEN }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          HOTJAR_ID: ${{ secrets.HOTJAR_ID }}
          HOTJAR_SNIPPET_VERSION: ${{ secrets.HOTJAR_SNIPPET_VERSION }}
        with:
          deploy-branch: 'master'
          access-token: ${{ secrets.AUTH_GITHUB_TOKEN }}
