name: 'Deploy Gatsby Application'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xmflsct/action-publish-gatsby
        with:
          publishBranch: 'public'
          token: ${{ secrets.AUTH_GITHUB_TOKEN }}
